# Generated by Django 4.0.4 on 2022-06-18 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_complaint_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
